import { defineConfig } from 'tsdown';

export default defineConfig({
  clean: true,
  dts: true,
  minify: false,
  publint: true,
  report: true,
  sourcemap: true,
  treeshake: true,

  unused: true,

  platform: 'node',
  target: 'es2020',

  format: ['cjs', 'esm'],

  banner: [
    '/**',
    ' * 🪶 Rune • v0.0.0',
    ' * ',
    ' * “Each rune carries a fragment of creation — what you build is the spell it becomes.”',
    ' * ',
    ' * @author Rune',
    ' * @copyright 2025 Rune',
    ' * @license MIT',
    ' * ',
    ' * This file is part of Rune and is automatically generated.',
    ' * Do not edit this file directly, unless you know what you are doing',
    ' * ',
    ' * @see {@link https://github.com/forgebyd/rune} for documentation',
    ' */',
    '',
  ].join('\n'),

  workspace: {
    include: ['examples/*', 'packages/*'],
  },
});
